### ISSUE TITLE
Diff Parsing: Multi-line macros with inline comments are not parsed completely 

### ISSUE THREAD

**Issue by AlexanderSchultheiss** [VariantSync/DiffDetective#102]
# Description
Macros can be defined in multiple lines by using line continuations with `\`. Additionally, macros can also become multi-line macros, if they contain C-Style comments that span multiple lines. The latter case is currently not handled by the parser, which results in broken formulas being extracted. 

# Example 
The following multi-line `#if` macro is possible, but not parsed completely: 
```diff
 # if A && \
 /* inline
 comment
 with multiple
 lines */ \
  B \
  && D
+   baz();
-   vaz();
 #endif
```
### Expected
The expected interpretation of the diff is:
```diff
 # if A && /* inline comment with multiple lines */   B   && D
+   baz();
-   vaz();
 #endif
```
### Actual (Issue)
However, the actual interpretation by the parser is:
```diff
 # if A && /* inline 
comment 
with multiple 
lines */   B   && D
+   baz();
-   vaz();
 #endif
```

# Proposed fix
The easiest solution is to track whether the current line is part of a C-style comment, and to consider the line incomplete if it is.

**Comment by AlexanderSchultheiss** [comment]
I implemented a fix and multiple test cases on my branch. These should be merged into develop eventually.

**Comment by pmbittner** [comment]
Never ending story. 😅 Thanks for pointing this out and potentially providing a fix. 🚀

**Comment by pmbittner** [comment]
Maybe we could cherry-pick your commits to a new branch based of develop, then create a pull-request?
