### ISSUE TITLE
Brackets in variable names upon boolean abstraction

### ISSUE THREAD

**Issue by pmbittner** [VariantSync/DiffDetective#47]
Upon boolean abstraction, names with brackets might be generated. For example `#if defined(A) && (B * 2) > C`
is abstracted to `A && (B__MUL__2)__GT__C` and the brackets become part of a variable's name. This is unfortunately confusing for some parsers or use cases. The brackets should be avoided if possible.

**Comment by pmbittner** [comment]
Another parser bug parses `#if` and `#elif` that are followed by only whitespace, as nodes (with a single literal with empty string as value) although a formula is missing.

**Comment by pmbittner** [comment]
This is already fixed, isn't it @ibbem ?

**Comment by ibbem** [comment]
Yes, this specific issue has been fixed. There is still an issue with brackets in character literals but this is documented and probably WONTFIX.
